apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste-nginx
  name: teste-nginx
spec:
  containers:
  - image: nginx
    name: teste-nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
